apiVersion: v1
kind: Service
metadata:
  name: banka-api-service
  namespace: banka
spec:
  selector:
    app: banka-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP