apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: banka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          env:
            - name: PGADMIN_EMAIL
              value: "admin@admin.com"
            - name: PGADMIN_PASSWORD
              value: "admin"
          ports:
            - containerPort: 80